---
- name: Appliance Mail
  hosts: all
  vars_files:
    - ../conf/appliance.secrets.conf.yml
    - ../conf/appliance.common.conf.yml
  roles:
    - geerlingguy.postfix 
  tasks:
    - name: Install additional mail utilities
      apt:
        name: ['mailutils']
        update_cache: yes

    - name: Open SMTP port(s)
      ufw: >
        rule=allow
        port={{ item }}
        proto=tcp
      with_items:
        - 25     # Default SMTP port
     
