---
- name: Citus Health Integration Engine (CHIE) CCF Containers
  hosts: all
  vars_files:
    - ../conf/appliance.secrets.conf.yml
    - ../conf/appliance.common.conf.yml
  tasks:
    - name: Clone Citus Health Integration Engine (CHIE) CCF Containers
      git:
       name: https://{{ chp_github_account | urlencode }}:{{ chp_github_account_token | urlencode }}@github.com/CitusHealthIntegrationEngine/{{ chp_github_accout_name }}.git
       dest: '{{citus_health_containers_path}}'
       force: yes

    - name: Create Appliance Admin User Common runtime config and Secrets directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - '{{ appliance_admin_user_common_runtime_config_directory }}'
        - '{{ appliance_admin_user_secrets_directory }}' 

   
